### PR TITLE
true chars for window

### PR DESCRIPTION
**Pull request by askovpen**
but vertical spaces wrong in your code.

### CODE REVIEW

**Comment by 6112** [comment]
The vertical spacing is wrong in Chrome, but is right in Firefox. I'll investigate that before changing the behavior of box().

**Comment by 6112** [comment]
Although not using the code from your commit (the code for the box() and border() functions had changed a lot by the time I saw your pull request), these Unicode characters are now used on the `dev` branch for the border() function. Vertical spacing is still unfixed for the demo font (Source Code Pro) in Chrome, but works fine if you use a BMP font, or even a few other fonts than Source Code Pro.

**Comment by askovpen** [comment]
Symbols for double border: ═,║,╗,╔,╚,╗

**Comment by 6112** [comment]
Added on `dev`, along with most ACS_* variables from ncurses (and more, where box drawing is concerned), and codepage 437 (for better BMP fonts).

**Comment by askovpen** [comment]
using cp437 - bad idea. only unicode! only hardcore!

**Pull request closed without merging**
